version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /Users/buritica/src/ha:/config  # change this to your configuration directory
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: false
    network_mode: host